#!/bin/sh


source ~/.bash/common/terminal.sh

#set -x

## set our local host name (eg. everything before the first period.)
myName=`uname -n | cut -f1 -d.`
mySystem=`uname -s`

eecho ''
eecho '(re-)sourcing your .bash/ configurations'

if [[ $mySystem == "Darwin" ]]; then
	eecho "System: Darwin"
        ## if my ~/.bash/mb$HOSTNAME file exists
        [ -f ~/.bash/mb-$myName.sh ] && eecho "file: mb-$myName" && time source ~/.bash/mb-$myName.sh
        [ -f ~/.bash/mbp-$myName.sh ] && eecho "file: mbp-$myName" && time source ~/.bash/mbp-$myName.sh
fi
        
if [[ $mySystem == "Linux" ]]; then
	eecho "System: Linux"
        ## if my ~/.bash/server-$HOSTNAME file exists
        [ -f ~/.bash/server-$myName.sh ] && eecho "file: server-$myName" && time source ~/.bash/server-$myName.sh

fi

